repos:
  - repo: local
    hooks:
      - id: lint
        name: Run pylint
        entry: make lint
        language: system
        types: [python]
      - id: format
        name: Run black
        entry: make format
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
