name: CI/CD

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build container
      run: |
        make build

      - name: Run container
        run: |
          make run
