name: Build and test container

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Build container
      run: |
        make build

    - name: Run container
      run: |
        make run

    - name: Test container
      run: |
        make test-container

    - name: Stop and remove container
      run: |
        make clean
